backend:
  name: git-gateway
  branch: main


media_folder: static/images
public_folder: ../../static/images/


collections:
  - name: "travel-packages"
    preview: false
    label: "Travel Packages"
    folder: "content/travel-packages"
    create: true
    slug: "{{slug}}"
    field:
      - { label: "Location", name: "location", widget: "string"}
      - { label: "travel Dates", name: "travel-dates", widget: "string"}
      - { label: "Featured Image", name: "featured-image", widgets: image}
      - { label: "Body", name: "body", widgets: "markdown"}
